AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable

Naming/MethodParameterName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
