# frozen_string_literal: true

require "test_helper"

class TestDay8 < Minitest::Test
  include AdventOfCode2024

  def test_part1
    assert_equal 14, Day8.part1(input)
  end

  def test_part2
    assert_equal 813, Day8.part2(input)
  end

  private

  def input
    <<~STR
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    STR
  end
end
